### ISSUE TITLE
Können wir Diskussionen für dieses Repository freischalten?

### ISSUE THREAD

**Issue by Naxos84** [Lector/DSA5maptool#1]
Hallo Lector,

Wir hatten auf Youtube geschrieben zu dem Video wo du das Framework vorgestellt hast.
Da die meisten deiner Kommentare verschwinden (und meine auch) machen wir halt hier weiter.

Da diese "issue" Funktion nicht primär für Diskussionen gedacht ist, würde ich mich freuen, wenn du in den Github-Repo Settings -> General -> Discussions 
ein Häkchen machst.

Gib mir einfach hier ein Zeichen, wenn das passt ;)
Alles weitere dann gern in den Diskussionen.

LG

**Comment by Lector** [comment]
Schön dass es trotz youtube geklappt hat.
Diskussionen sind hiermit eröffnet.
