### ISSUE TITLE
Bug: Campaign window empty when hosting server on a Mac (M1)

### ISSUE THREAD

**Issue by thebodo** [Lector/DSA5maptool#20]
## Prerequisite:

- Have a Mac
- Use MapTool 1.13.2
- Use DSA5maptool 1.3.1

## Steps to reproduce

1. Load campaign
2. Start Server on Mac
3. Connect from another computer
4. Open campaign window (window -> campaign

## Actual Result

Campaign window is empty

## Expected Result

Campaign window show sections like "1- Chat, 2 - Würfel, 3 - Charakter ..."

**Comment by Lector** [comment]
One potential reason why players might not receive the campaign macros could be a setting you configure during launch called 'players get campaign macros.' Here's a screenshot of my MapTool version:
![image](https://github.com/Lector/DSA5maptool/assets/765587/ac7d2c45-cb5b-44b4-9a98-08d66b744e9c)
If this does not solve the problem im going to test this as soon as I have access to a Mac, which should be tomorrow.

**Comment by thebodo** [comment]
Just tested it, this solves the issue.. My fault, thank you for your quick reply.
